./HSV-Histogram simbrashIce.png >> output.csv
./HSV-Histogram simbrashIce1.png >> output.csv
./HSV-Histogram simbrashIceForeward.png >> output.csv
./HSV-Histogram simBrashIceYellow.png >> output.csv
./HSV-Histogram simLakeIce1.png >> output.csv
./HSV-Histogram simLakeIce2.png >> output.csv
./HSV-Histogram simLakeIceAnemones.png >> output.csv
./HSV-Histogram simLakeIceCrackYellowPurple.png >> output.csv
./HSV-Histogram simLakeIceGreenShrimp.png >> output.csv
./HSV-Histogram simLakeIceSlug.png >> output.csv
./HSV-Histogram simPlateletIce.png >> output.csv
./HSV-Histogram simvoronoiIce1.png >> output.csv