./HSV-Histogram Anemone1.jpg >> output.csv
./HSV-Histogram Anemone2.jpg >> output.csv
./HSV-Histogram greenIce1.png >> output.csv
./HSV-Histogram greenIce2.png >> output.csv
./HSV-Histogram greenIce3.png >> output.csv
./HSV-Histogram greenIce4.png >> output.csv
./HSV-Histogram greenIce5.png >> output.csv
./HSV-Histogram greenIce6.png >> output.csv
./HSV-Histogram greenIce7.png >> output.csv
./HSV-Histogram greenIce8.png >> output.csv
./HSV-Histogram icefinUnderIce.png >> output.csv

./HSV-Histogram jettyIce1.png >> output.csv
./HSV-Histogram jettyIce2.png >> output.csv
./HSV-Histogram jettyIce4.png >> output.csv
./HSV-Histogram jettyIce12.png >> output.csv
./HSV-Histogram jettyIce13.png >> output.csv
./HSV-Histogram jettyIce23.png >> output.csv
./HSV-Histogram jettyIce25.png >> output.csv

./HSV-Histogram JettyIce5216274_frame19672.png >> output.csv
./HSV-Histogram JettyIce5216274_frame33557.png >> output.csv
./HSV-Histogram JettyIce5216274_frame45293.png >> output.csv
./HSV-Histogram JettyIce5216274_frame49474.png >> output.csv
./HSV-Histogram JettyIce5216274_frame51556.png >> output.csv
./HSV-Histogram JettyIce5216274_frame114489.png >> output.csv

#./HSV-Histogram movingSeaStar.png >> output.csv
#./HSV-Histogram randomLife.png >> output.csv
#./HSV-Histogram randomLife2.png >> output.csv
#./HSV-Histogram seaAnemonie.png >> output.csv
#./HSV-Histogram seaSlug.png >> output.csv
#./HSV-Histogram seaSponge.png >> output.csv
#./HSV-Histogram seaStar.png >> output.csv
#./HSV-Histogram seaStar2.png >> output.csv
#./HSV-Histogram seaStarAndSponge.png >> output.csv
#./HSV-Histogram seaStarClose.png >> output.csv
#./HSV-Histogram seaSun.png >> output.csv
#./HSV-Histogram shrimp.png >> output.csv
